export const CABIAO_BARANGAYS = [
  'Bagong Sikat',
  'Bulac',
  'Caballero',
  'Cabisuculan',
  'Calabasa',
  'Canantong',
  'Capital',
  'Cardona',
  'Cuyapa',
  'Dunlapihan',
  'Gulagul',
  'Gulod',
  'Imbuñga',
  'Labi',
  'Lagare',
  'Laguerta',
  'La Palma',
  'Layac',
  'Maligaya',
  'Manaul',
  'Mangga',
  'Maycaban',
  'Naglabrahan',
  'Nagpandayan',
  'Paitan Norte',
  'Paitan Sur',
  'Palestina',
  'Panorama',
  'Peñaranda',
  'Pinili',
  'Punt Mesa',
  'Pulong Bahay',
  'Sampalucan',
  'San Isidro',
  'San Jose',
  'San Juan',
  'San Rafael',
  'Santa Cruz',
  'Santa Lucia',
  'Santo Tomas',
  'Sinipit',
  'Tagtagumbao',
  'Tumana',
  'Villa Nati',
]

export const BUSINESS_CATEGORIES = [
  { value: 'food_dining', label: 'Food & Dining' },
  { value: 'retail_shopping', label: 'Retail & Shopping' },
  { value: 'accommodation', label: 'Accommodation' },
  { value: 'tourism_recreation', label: 'Tourism & Recreation' },
  { value: 'services', label: 'Services' },
  { value: 'agriculture', label: 'Agriculture' },
  { value: 'other', label: 'Other' },
]

export function getCategoryLabel(value) {
  return BUSINESS_CATEGORIES.find(c => c.value === value)?.label || value
}
